### You need to bind XSUAA and destination service instance by below commands
### cds bind -2 sap-sample-fiori-elements-uploadset-auth
### cds bind -2 sap-sample-fiori-elements-uploadset-destination
### Then change "kind": "xsuaa-auth" to "kind": "mocked" in .cdsrc-private.json

### Authentication setting of Hybrid testing
@serviceUrl = http://localhost:4004

### Create Template Request
# @name createTemplateRequest
POST {{serviceUrl}}/odata/v4/user/TemplateRequests
Authorization: Basic alice:123
Content-Type: application/json

{
    "title": "Dummy title",
    "description": "Dummy description",
    "comment" : ""
}

### Extract Template Request ID
@templateRequestId = {{createTemplateRequest.response.body.$.ID}}

### Create File Object
# @name createFile
POST {{serviceUrl}}/odata/v4/user/TemplateRequests(ID={{templateRequestId}},IsActiveEntity=false)/attachments
Authorization: Basic alice:123
Content-Type: application/json

{
    "name": "thumb.png"
}

### Extract File Object ID
@fileId = {{createFile.response.body.$.ID}}

### Upload File Content
PUT {{serviceUrl}}/odata/v4/user/Attachments('{{fileId}}')/content
Authorization: Basic alice:123
Content-Type: image/png

< ./thumb.png

### Download File
GET {{serviceUrl}}/odata/v4/user/TemplateRequests(ID={{templateRequestId}},IsActiveEntity=false)/attachments('{{fileId}}')/content
Authorization: Basic alice:123

### Save Template Request
POST {{serviceUrl}}/odata/v4/user/TemplateRequests(ID={{templateRequestId}},IsActiveEntity=false)/UserService.draftActivate
Authorization: Basic alice:123
Content-Type: application/json

{}

### Download File after saving Template Request
GET {{serviceUrl}}/odata/v4/user/TemplateRequests(ID={{templateRequestId}},IsActiveEntity=true)/attachments('{{fileId}}')/content
Authorization: Basic alice:123

### Delete File Object
DELETE {{serviceUrl}}/odata/v4/user/Attachments('{{fileId}}')
Authorization: Basic alice:123
